# Generated by Django 3.1 on 2020-09-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200909_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Post',
            new_name='post',
        ),
    ]
